id: P2FAC4232
initial_creation_type: ocr
source_metadata:
  volumes:
    41a15d3eda864b09ab9930599bf501a2:
      base_file: v072.txt
      image_group_id: I1PD95917
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་ལས་དངོས་གཞིའི་ས་མང་པོ།
      total_pages: 1406
      volume_number: 72
