id: P2FAC4232
initial_creation_type: ocr
source_metadata:
  volumes:
    88a4bb9174f043db902032e8a56e07f4:
      base_file: v072.txt
      image_group_id: I1PD95917
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་ལས་དངོས་གཞིའི་ས་མང་པོ།
      total_pages: 1406
      volume_number: 72
